services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules
            - .next